/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.operator.jsonc --include-runtime=false --env-interface=OperatorBindings worker-configuration.operator.d.ts` (hash: 45880b4f51307ca8e51b3eb0fdc968d6)
interface __BaseEnv_OperatorBindings {
	BILLING_DB: D1Database;
	DOMAIN_EVENTS: Queue;
	APP_ENV: "development";
	OPERATOR_ACCESS_ENABLED: "0";
	BILLING_ACCOUNTS: DurableObjectNamespace /* BillingAccount from serp-dev-lago-native */;
	PLAN_DELETION_WORKFLOW: Workflow /* PlanDeletionWorkflow from serp-dev-lago-native */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/operator/index");
	}
	interface Env extends __BaseEnv_OperatorBindings {}
}
interface OperatorBindings extends __BaseEnv_OperatorBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "OPERATOR_ACCESS_ENABLED">> {}
}
