/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.portal.jsonc --include-runtime=false --env-interface=PortalBindings worker-configuration.portal.d.ts` (hash: 5b4a240395f120dd8c19ad2dae78aaa7)
interface __BaseEnv_PortalBindings {
	BILLING_ARTIFACTS: R2Bucket;
	BILLING_DB: D1Database;
	APP_ENV: "development";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/portal/index");
	}
	interface Env extends __BaseEnv_PortalBindings {}
}
interface PortalBindings extends __BaseEnv_PortalBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV">> {}
}
