/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.operator.jsonc --include-runtime=false --env-interface=OperatorBindings worker-configuration.operator.d.ts` (hash: 0600eb557c8c501aa4ee8f7906be827b)
interface __BaseEnv_OperatorBindings {
	BILLING_DB: D1Database;
	DOMAIN_EVENTS: Queue;
	APP_ENV: "development";
	OPERATOR_ACCESS_ENABLED: "1";
	ACCESS_TEAM_DOMAIN: "https://serpcompany.cloudflareaccess.com";
	ACCESS_AUD: "4e2aeb75eccbd0abda500c9318a371acbeab7a244f8727904358021daea5a951";
	BILLING_ACCOUNTS: DurableObjectNamespace /* BillingAccount from serp-dev-lago-native */;
	PLAN_DELETION_WORKFLOW: Workflow /* PlanDeletionWorkflow from serp-dev-lago-native */;
	DOCUMENT_WORKFLOW: Workflow /* DocumentWorkflow from serp-dev-lago-native */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/operator/index");
	}
	interface Env extends __BaseEnv_OperatorBindings {}
}
interface OperatorBindings extends __BaseEnv_OperatorBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "OPERATOR_ACCESS_ENABLED" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD">> {}
}
