/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.operator.jsonc --include-runtime=false --env-interface=OperatorBindings worker-configuration.operator.d.ts` (hash: 2868124426f7e48fb69a91f92c8830a2)
interface __BaseEnv_OperatorBindings {
	BILLING_DB: D1Database;
	APP_ENV: "development";
	OPERATOR_ACCESS_ENABLED: "0";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/operator/index");
	}
	interface Env extends __BaseEnv_OperatorBindings {}
}
interface OperatorBindings extends __BaseEnv_OperatorBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "OPERATOR_ACCESS_ENABLED">> {}
}
